# Generated by Django 3.1.1 on 2020-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rut_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutplant',
            name='moistureLevel',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
    ]
